# resources:
#   - name: r_bitbucket
#     type: GitRepo
#     configuration:
#       gitProvider: i_bitbucket1
#       path: shiptest-rc-me/vijay-tests

resources:
  - name: r_github 
    type: GitRepo
    configuration:
      gitProvider: i_GitHub
      path: Ranjansingh41/u16all

# resources:
#   - name: simple_test
#     type: GitRepo
#     configuration:
#       gitProvider: ranjan_github
#       path: Ranjansingh41/test 
      
pipelines:
  - name: pipeline_test
    steps:
      - name: cpp
        type: Bash
        configuration:
#           timeoutSeconds: 20
#           nodePool: u18node
          inputResources:
            - name: r_github 
#           outputResources:
#             - name: simple_test1
          runtime:
            type: image
            image:
#               auto:
#                 language: java
#                 versions: 
#                   - "11"
              custom:
                name: drydock/u16phpall125
                tag: master
                autoPull: true
        execution:
#           onStart:
#             - printen
          onExecute:
            - python --version
#           onFailure:
#             - echo "test fail"
#           onComplete: #always
#             - echo "Cleaning up some stuff"


#       - name: go
#         type: Bash
#         configuration:
#           priority: 2
#           inputSteps:
#             - name: node
#           runtime:
#             type: image
#             image:
# #               auto:
# #                 language: go
# #                 versions:
# #                   - 1.12.6
#               custom:
#                 name: drydock/u18go
#                 tag: master
#                 autoPull: false
#         execution:
#           onExecute:
#             - source /root/.gvm/scripts/gvms
#             - gvm list
#             - go 
# #             - gvm use 1.11.11 
# #             - go version
# #             - gvm use 1.12.6
# #             - go version 
#           onSuccess:
#             - echo "Job well done!"
            
#       - name: cpp
#         type: Bash
#         configuration:
#           priority: 10        
#           inputSteps:
#             - name: node
#           runtime:
#             type: image
#             image:
#               auto:
#                 language: cpp
#                 versions:
#                   - 8.0.0
# #               custom:
# #                 name: drydock/u18cpp
# #                 tag: master
# #                 autoPull: true
#         execution:
#           onExecute:
#             - gcc --version
#             - clang --version
