# resources:
#   - name: r_bitbucket
#     type: GitRepo
#     configuration:
#       gitProvider: i_bitbucket1
#       path: shiptest-rc-me/vijay-tests

resources:
  - name: r_github 
    type: GitRepo
    configuration:
      gitProvider: i_GitHub
      path: Ranjansingh41/u16all

# resources:
#   - name: simple_test
#     type: GitRepo
#     configuration:
#       gitProvider: ranjan_github
#       path: Ranjansingh41/test 
      
pipelines:
  - name: pipeline_ranjan
    steps:
      - name: node
        type: Bash
        configuration:
          timeoutSeconds: 20
          inputResources:
            - name: r_github 
#           outputResources:
#             - name: simple_test1
          runtime:
            type: image
            image:
# #               auto:
# #                 language: go
# #                 Versions: 
# #                  - 1.12.6
              custom:
                name: ankul/u16
                tag: master
        execution:
#           onStart:
#             - printen
          onExecute:
            - sleep 60
#           onFailure:
#             - echo "test fail"
#           onComplete: #always
#             - echo "Cleaning up some stuff"


      - name: go
        type: Bash
        configuration:
          priority: 2
          inputSteps:
            - name: node
          runtime:
            type: image
            image:
#               auto:
#                 language: go
#                 versions:
#                   - 1.12.6
              custom:
                name: drydock/u18go
                tag: master
                autoPull: false
        execution:
          onExecute:
            - source /root/.gvm/scripts/gvm
            - gvm list
             - go version
#             - gvm use 1.11.11 
#             - go version
#             - gvm use 1.12.6
#             - go version 
          onSuccess:
            - echo "Job well done!
            
      - name: cpp
        type: Bash
        configuration:
          priority: 10        
          inputSteps:
            - name: node
          runtime:
            type: image
            image:
              auto:
                language: cpp
                versions:
                  - 8.0.0
#               custom:
#                 name: drydock/u18cpp
#                 tag: master
#                 autoPull: true
        execution:
          onExecute:
            - gcc --version
            - clang --version
