pipelines:
  - name: pipeline_affinityGroup_example
    steps:
      - name: ag_step_1
        type: Bash
        configuration:
          affinityGroup: together
        execution:
          onExecute:
            - echo $"hi"
      - name: ag_step_2
        type: Bash
        configuration:
          affinityGroup: together
          inputSteps:
             - name: ag_step_1
        execution:
          onExecute:
            - echo $"hello"
      - name: ag_step_3
        type: Bash
        configuration:
          affinityGroup: together
          inputSteps:
             - name: ag_step_2
        execution:
          onExecute:
            - echo $"hello"      
