resources:
  - name: app1
    type: gitRepo
    repoPath: Ranjansingh41/test
    configuration:
      integrationName: github
      branches:
        only: master
    initialVersion:
      sha: master

pipelines:

  - name: test_pipeline
    steps:
      - name: test_func
        type: bash
        configuration:
          affinityGroup: build
        setup:
          runtime:
            type: image
            image:
              auto:
                language: nodeJs
                versions:
                  - 10.15.3
        triggeredBy:
          resources:
            - app1
        execution:
          onExecute:
            - printenv
