resources:
  - name: gitResource
    type: GitRepo
#     repoPath: ranjansingh41/test
    configuration:
      gitProvider: ranjan_github
      path: Ranjansingh41/test
#       files:
#         only: README|install.sh|node
      branches:
        only: master
#       tags:
#         only: tagv*
#       buildOn:
#         commit: false
#       shallowDepth: 2
    version:
      sha: master
      
pipelines:
  - name: pipeline12
    steps:    
      - name: test1
        type: bash
        setup:
          environmentVariables:
            readOnly:
              ENV1: ranjan
              ENV2: kumar    
          runtime:
            type: image
            image:
  #               auto:
  #                 language: nodejs
  #                 versions:
  #                   - 10.15.3
              custom:
                name: drydock/u16node
                tag: master
        triggeredBy:
          resources:
            - gitResource  
        execution:
          onExecute:
            - node --version
#         outputResources:
#           - test10

            
      - name: default_version
        type: bash
#         configuration:
#             affinityGroup: sita 
#             nodePool: kermit_ubuntu_pool
        triggeredBy:
         steps:
           - test1
        setup:
         runtime:
           type: image
           image:
             auto:
               language: 10.16.3                  
        execution:
           onExecute:
             - echo - echo TEST_FOR_DEFAULT_VERSION
             - node -v
