resources:
  - name: mvnBuild_inf
    type: BuildInfo
    configuration:
      sourceArtifactory: varsha_artifactory
      buildName: mvn_sample_build
      buildNumber: 1
      
pipelines:
  - name: mvntest_ranjan
    steps:
      - name: mvnBuild_sample
        type: MvnBuild
        configuration:
          affinityGroup: mvnbuild
#           nodePool: ubuntu16
          sourceLocation: ./artifactory-maven-plugin-example
          mvnCommand: clean install -f ./pom.xml
          configFileLocation: .
          configFileName: mvn-art-config
          inputResources:
            - name: mvnBuild_inf
#           inputSteps:
#             - name: mvnBuild_info1
          integrations:
            - name: varsha_artifactory
            - name: varsha_slack
          runtime:            
            type: image
            image:
              custom:
                name: pipelines-docker.jfrog.io/jfrog/pipelines-u16java:0.9.0
                tag: master
        execution:
          onStart:
            - javac -version
            - mvn --version
          onSuccess:
            - send_notification varsha_slack      
