resources:
  - name: jenkins1
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: test
      buildNumber: 1
 
pipelines:
  - name: simple_pieplines
    steps:          
      - name: test_Jenkins
        type: Jenkins
        configuration:
          integrations:
            - name: jenkins
          outputResources:
            - name: jenkins1
  
      - name: stepB
        type: Bash
        configuration:
          inputSteps:
            - name: test_Jenkins
        execution:
          onExecute:
            - echo "executing stepB..."
