resources:
  - name: npm_project
    type: GitRepo
    configuration:
      gitProvider: ranjan_github
      path: ranjansingh41/j-sample-node
#       sha: npmtest.yml
       
  - name: publish_info
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildNumber: 1
      buildName: npm-testing
      
  - name: npm_build_promote
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildNumber: 1
      buildName: npm-testing
      
pipelines:
  - name: test_pipeline_ranjan
    steps:
      - name: start_npm_build
        type: NpmBuild
        configuration:
          repositoryName: test-npm-local
#           nodepool: ubuntu16
          sourceLocation: .
          inputResources:
            - name: npm_project
          integrations:
            - name: varsha_artifactory
            
      - name: start_npm_pub_autopub_true
        type: NpmPublish
        configuration:
          repositoryName: test-npm-local
#           nodepool: ubuntu16
          autoPublishBuildInfo: true
          inputSteps:
            - name: start_npm_build
          integrations:
            - name: varsha_artifactory
          outputResources:
            - name: publish_info
            
      - name: promote
        type: PromoteBuild
        configuration:
          targetRepository: promote-test
#           nodepool: ubuntu16
          inputResources:
            - name: publish_info
#               trigger: false
          outputResources:
            - name: npm_build_promote 
            
     
          
