resources:
  - name: app2
    type: gitRepo
    repoPath: ranjansingh41/u16
    configuration:
      integrationName: github
      files:
        except: README
      branches:
        only: master
#       tags:
#         only: tagv*
#       shallowDepth: 2
    initialVersion:
      sha: master
#     buildOn:
#       tagPush: true
      
#   - name: app1
#     type: gitRepo
#     repoPath: ranjansingh41/test
#     configuration:
#       integrationName: github
#       branches:
#         only: master
#     initialVersion:
#       sha: master    

pipelines:
  - name: pipeline1
    steps:
       - name: step1
         type: bash
#          configuration:
#           affinityGroup: bldGroup 
#             priority: 1
         triggeredBy:
           resources:
             - app2

         setup:
           runtime:
             type: image
            # image:
               #auto:
#                  language: none            
         execution:
           onExecute:
             - printenv
#              - sudo apt-get install tree
#              - git log
#              - node -v

#        - name: trigger1
#          type: bash
# #          configuration:
# #           affinityGroup: bldGroup 
# #             priority: 3

#          triggeredBy:
#            resources:
#              - app1
#          setup:
#            runtime:
#              type: image
#              image:
#                auto:
#                  language: nodejs
#                  versions:
#                    - 8.16.0                      
#          execution:
#            onExecute:
#              - echo TEST_FOR_SELECTED_VERSION
#              - node -v
             
#        - name: trigger2
#          type: bash
#          configuration:
# #           affinityGroup: bldGroup 
#             priority: 2
#          triggeredBy:
#            steps:
#              - step1
#          setup:
#            runtime:
#              type: image
#              image:
#                auto:
#                  language: nodejs   
#          triggeredBy:
#           resources:
#             - app1
#          execution:
#            onExecute:
#              - echo - echo TEST_FOR_DEFAULT_VERSION
#              - node -v
             
#        - name: utility_step
#          type: bash
#          triggeredBy:
#            resources:
#              - app1
#          requires:
#            integrations:
#              - slackNotify
#          execution:
#            onExecute:
#              - update_commit_status app1 --status processing --message "updated in utility step" --context $STEP_NAME
#              - send_notification slackNotify


#   - name: pipeline2
#     steps:
#         - name: none_language
#           type: bash
#           configuration:
# #           affinityGroup: bldGroup 
#             priority: 2

#           setup:
#             runtime:
#               type: image
#              # image:
#                 #auto:
#   #                  language: none            
#           execution:
#             onExecute:
#               - echo TEST_FOR_NONE
#   #              - node -v

#         - name: selected_version
#           type: bash
#           triggeredBy:
#             steps:
#                - none_language
# #           requires:
# #             steps:
# #               - none_language
#           setup:
#             runtime:
#               type: image
#               image:
#                 auto:
#                   language: nodejs
#                   versions:
#                     - 8.16.0                      
#           execution:
#             onExecute:
#               - echo TEST_FOR_SELECTED_VERSION
#               - node -v
 
# #         - name: default_version
# #           type: bash
# #            triggeredBy:
# #            steps:
# #              - none_language
# #           requires:
# #             steps:
# #               - none_language
# #           setup:
# #             runtime:
# #               type: image
# #               image:
# #                 auto:
# #                   language: nodejs   
# # #           triggeredBy:
# #            resources:
# #              - app1
# #           execution:
# #             onExecute:
# #               - echo - echo TEST_FOR_DEFAULT_VERSION
# #               - node -v

#   #                     - name: utility_step
#   #                       type: bash
#   #                       triggeredBy:
#   #                         resources:
#   #                           - app1
#   #                       requires:
#   #                         integrations:
#   #                           - slackNotify
#   #                       execution:
#   #                         onExecute:
#   #                           - update_commit_status app1 --status processing --message "updated in utility step" --context $STEP_NAME
#   #                           - send_notification slackNotify

             
             
             
             
             
