resources:
  - name: npm_project
    type: GitRepo
    configuration:
      gitProvider: ranjan_github
      path: ranjansingh41/j-sample-node
       
  - name: publish_info
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildNumber: 1
      buildName: npm-testing
      
  - name: npm_build_promote
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildNumber: 1
      buildName: npm-testingPromote
      
pipelines:
  - name: Demo
    steps:
      - name: npm_build
        type: NpmBuild
        configuration:
          repositoryName: npm-awsdemo
#           nodePool: aws-demo-pool-2
          sourceLocation: .
          inputResources:
            - name: npm_project
          integrations:
            - name: art
#         execution:
#           onSuccess:
#             - send_notification Demo_slack
      - name: npm_publish
        type: NpmPublish
        configuration:
          repositoryName: npm-awsdemo
#           nodePool: aws-demo-pool-2
          autoPublishBuildInfo: true
          inputSteps:
            - name: npm_build
          integrations:
            - name: art
          outputResources:
            - name: publish_info
        
             
      - name: npm_promote
        type: PromoteBuild
        configuration:
          targetRepository: npm-demo
#           nodePool: aws-demo-pool-2
          inputResources:
            - name: publish_info
#               trigger: false
          outputResources:
            - name: npm_build_promote 
        
          
     
          
