resources:
  - name: real_npm_project
    type: GitRepo
    configuration:
      gitProvider: ranjan_github
      path: ranjansingh41/test 
      
pipelines:
  - name: pipeline_ranjan
    steps:
      - name: go
        type: GoBuild
        configuration:
          runtime:
            type: image
            image:
#               auto:
#                 language: java
#                 versions:
#                   - openjdk8
              custom:
                name: drydock/u16go
                tag: latest
                autoPull: false      
#           inputResources:
#             - name: gitResource123
        execution:
          onStart:
             - jfrog --version
#             - printenv 
#             - java -version
#             - _set_jdk openjdk8
#             - java -version
#             - echo $JAVA_HOME
#             - echo $PATH
#             - _set_jdk openjdk11
#             - java -version
#             - echo $JAVA_HOME
#             - echo $PATH
#             - mvn --version
#             - ant -version
#       - name: go
#         type: Bash
#         configuration:
#           inputSteps:
#             - name: java      
#           runtime:
#             type: image
#             image:
# #               auto:
# #                 language: go
# #                 versions:
# #                   - 1.12.5
#               custom:
#                 name: drydock/u18go
#                 tag: master
#                 autoPull: false
#         execution:
#           onExecute:
#             - source /root/.gvm/scripts/gvm
#             - gvm list
#             - go version
#             - gvm use 1.11.10 
#             - go version
#             - gvm use 1.12.5
#             - go version                
#       - name: cpp
#         type: Bash
#         configuration:
# #           nodePool: vijay_node           
#           inputSteps:
#             - name: go      
#           runtime:
#             type: image
#             image:
# #               auto:
# #                 language: c
# #                 versions:            
#               custom:
#                 name: drydock/u18cpp
#                 tag: master
#                 autoPull: true
#         execution:
#           onExecute:
#             - gcc --version
#             - clang --version
