resources:
  - name: test10
    type: gitRepo
    repoPath: ranjansingh41/test
    configuration:
      integrationName: ranajn_github
#       files:
#         only: README|install.sh|node
      branches:
        only: master
#       tags:
#         only: tagv*
#       buildOn:
#         commit: false
#       shallowDepth: 2
    initialVersion:
      sha: master
      
# resources:
#   - name: fileIntegrationResource
#     type: file
#     fileLocation: <string>
#     fileName: <string>  # optional
#     configuration:      
#       integrationName: fileIntegration
#     initialVersion:
#       fileDtTm: <string>  # optional

pipelines:
  - name: pipeline14
    setup:
      environmentVariables:
        readOnly:
          NameF: ranjan
          NameL: singh
    steps:    
      - name: test1
        type: bash
        setup:
          environmentVariables:
            normal:
              NameF: ranjan
              NameL: singh       
#           runtime:
#             type: image
#             image:
#              custom:
#                name: drydock/u16all
#                tag: master
#         triggeredBy:
#           resources:
#             - testing_1
        execution:
          onExecute:
            - echo "test1"
            - echo "NameL=$NameL"
            - echo "NameF=$NameF"

#        - name: selected_version
#          type: bash
# #          setup:
# #            environmentVariables:
# #              readOnly:
# #                ENV1: value1
# #                ENV2: value2 
#          triggeredBy:
# #          requires:
#            steps:
#              - none_language
#          setup:
#            runtime:
#              type: image
#              image:
#                auto:
#                  language: nodejs
#                  versions:
#                    - 8.16.0                      
#          execution:
#            onExecute:
#              - echo TEST_FOR_SELECTED_VERSION
#              - node -v
             
#        - name: default_version
#          type: bash
#          triggeredBy:
# #          requires:
#            steps:
#              - none_language
#          setup:
#            runtime:
#              type: image
#              image:
#                auto:
#                  language: nodejs                  
#          execution:
#            onExecute:
#              - echo - echo TEST_FOR_DEFAULT_VERSION
#              - node -v
