resources:
  - name: test10
    type: gitRepo
    repoPath: ranjansingh41/test
    configuration:
      integrationName: ranajn_github
#       files:
#         only: README|install.sh|node
      branches:
        only: master
#       tags:
#         only: tagv*
#       buildOn:
#         commit: false
#       shallowDepth: 2
    version:
      sha: master
      
# resources:
#   - name: fileIntegrationResource
#     type: file
#     fileLocation: <string>
#     fileName: <string>  # optional
#     configuration:      
#       integrationName: fileIntegration
#     initialVersion:
#       fileDtTm: <string>  # optional

pipelines:
  - name: pipeline12
    setup:
      environmentVariables:
        readOnly:
          NameF: ranjan
          NameL: kumar
    steps:    
      - name: test1
        type: bash
        setup:
#           environmentVariables:
#             normal:
#               NameF: singh
#               NameL: umar       
          runtime:
            type: image/custom
#             type: host
            image:
#                 auto:
#                   language: nodejs
#                   versions: 10.15.3
             custom:
               name: drydock/u16node30
               tag: master
        triggeredBy:
          resources:
            - test10
        execution:
          onExecute:
            - echo $?
            - echo "test1"
            - echo "NameL=$NameL"
            - echo "NameF=$NameF"
            - nvm list
            
