resources:
  - name: simple_test
    type: GitRepo
    configuration:
      gitProvider: ranjan_github
      path: Ranjansingh41/test 
      
pipelines:
  - name: pipeline_ranjan
    steps:
      - name: node
        type: Bash
        configuration:
          inputResources:
            - name: simple_test
          runtime:
            type: image
            image:
              auto:
                language: nodejs
                versions:
                  - 10.16.0
#               custom:
#                 name: drydock/u16node
#                 tag: master
#                 autoPull: false
        execution:
          onExecute:
            - nvm list
            - node --version 
            - add_run_variables imageTag="master"


#       - name: go
#         type: Bash
#         configuration:
#           inputSteps:
#             - name: node
#           runtime:
#             type: image
#             image:
#               auto:
#                 language: go
#                 versions:
#                   - 1.12.6
# #               custom:
# #                 name: drydock/u18go
# #                 tag: master
# #                 autoPull: false
#         execution:
#           onExecute:
#             - source /root/.gvm/scripts/gvm
#             - gvm list
#             - go version
#             - gvm use 1.11.11 
#             - go version
#             - gvm use 1.12.6
#             - go version                
#       - name: cpp
#         type: Bash
#         configuration:
# #           nodePool: vijay_node           
#           inputSteps:
#             - name: go      
#           runtime:
#             type: image
#             image:
#               auto:
#                 language: c
#                 versions:
#                   - 8.0.0
# #               custom:
# #                 name: drydock/u18cpp
# #                 tag: master
# #                 autoPull: true
#         execution:
#           onExecute:
#             - gcc --version
#             - clang --version
