pipelines:
  - name: pipeline_S_PS_Language_0003
    steps:
      - name: S_PS_Language_0003
        type: PowerShell
        configuration:
          nodePool: win_2019
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - 13
        execution:
          onExecute:
            - java -version
#             - if($(java -version) -ne "openjdk version "1.8.0_232""){
#               Write-Error "Stop" -ErrorAction Stop
#               }
#             - |
#               [[ "$(node --version)" == *"10.18.0"* ]]
#             - gci env:*
#             - ls Env:
#             - get-childitem -path env:* | get-stepname
#             -  ("$java -version === $13.0.1")
#             - "java -version[]" == "13.0.1[]"
#             - get-childitem env
#             - Get-Variable | format-table
#             - java -version
#             - ant -version
#             - mvn -v
#             - gradle -v
#             - node -v
#             - npm --version
            
#             - |
#               [[ "$(java -version)" == *"13.0.1"* ]]



# resources:
#   - name: test1234
#     type: GitRepo
#     configuration:
#       gitProvider: github1
#       path: Ranjansingh41/test
      
# pipelines:
#   - name: pipelines
#     steps:
#       - name: S_Bash1
#         type: Bash
#         configuration:
#           inputResources:
#             - name: test1234
#         execution:
#           onExecute:
#             - echo "hi"
#       - name: S_Bash2
#         type: Bash
#         configuration:
#           inputSteps:
#             - name: S_Bash1
#         execution:
#           onExecute:
#             - echo "executing step..."
            
#       - name: S_Bash3
#         type: Bash
#         configuration:
#           inputResources:
#             - name: test1234
#         execution:
#           onExecute:
#             - echo "hi"
#       - name: S_Bash4
#         type: Bash
#         configuration:
#           inputSteps:
#             - name: S_Bash3
#         execution:
#           onExecute:
#             - echo "executing step..."
