# resources:
#   - name: S_Bash_0007_propertyBag
#     type: PropertyBag
#     configuration:
#       property1: "test"

pipelines:
  - name: pipelines_S_Bash
    steps:
      - name: S_Bash_propertyBag
        type: Bash
#         configuration:
#           inputResources:
#             - name: S_Bash_0007_propertyBag
        execution:
          onExecute:
            - printenv
#             - echo "$property1"
#             - echo "$property2"
#             - |
#               [ ! -z "$res_S_Bash_0007_propertyBag_property2"  ]
