resources:
  - name: npm_project
    type: GitRepo
    configuration:
      gitProvider: ranjan_github
      path: ranjansingh41/j-sample-node
       
  - name: publish_info
    type: BuildInfo
    configuration:
      sourceArtifactory: art_aws_demo
      buildNumber: 1
      buildName: npm-testing
      
  - name: npm_build_promote
    type: BuildInfo
    configuration:
      sourceArtifactory: art_aws_demo
      buildNumber: 1
      buildName: npm-testingPromote
      
pipelines:
  - name: Demo
    steps:
      - name: npm_build
        type: NpmBuild
        configuration:
          repositoryName: npm-remote-cache
          nodePool: aws-demo-pool-2
          sourceLocation: .
          inputResources:
            - name: npm_project
          integrations:
            - name: art_aws_demo
        execution:        
          onSuccess:
            - send_notification Demo_slack
#           onFailure:
#             - send_notification Demo_slack
#           onComplete:
#             - send_notification Demo_slack
    
      - name: npm_publish
        type: NpmPublish
        configuration:
          repositoryName: npm-remote-cache
          nodePool: aws-demo-pool-2
          autoPublishBuildInfo: true
          inputSteps:
            - name: npm_build
          integrations:
            - name: art_aws_demo
          outputResources:
            - name: publish_info
        execution:        
          onSuccess:
            - send_notification Demo_slack
          onFailure:
            - send_notification Demo_slack
          onComplete:
            - send_notification Demo_slack
             
      - name: npm_promote
        type: PromoteBuild
        configuration:
          targetRepository: npm-demo
          nodePool: aws-demo-pool-2
          inputResources:
            - name: publish_info
#               trigger: false
          outputResources:
            - name: npm_build_promote 
        execution:        
          onSuccess:
            - send_notification Demo_slack
          onFailure:
            - send_notification Demo_slack
          onComplete:
            - send_notification Demo_slack    
     
          
