resources:
  - name: app4
    type: gitRepo
    repoPath: ranjansingh41/test
    configuration:
      integrationName: 
#       files:
#         only: README|install.sh|node
      branches:
        only: master
      tags:
        only: tagv*
      buildOn:
#         commit: false
#       shallowDepth: 2
    initialVersion:
      sha: master
      
pipelines:
  - name: pipeline
    steps:
       - name: none_language
         type: bash
         setup:
           runtime:
             type: image
            # image:
               #auto:
#                  language: none            
         execution:
           onExecute:
             - echo TEST_FOR_NONE
#              - node -v

       - name: selected_version
         type: bash
         requires:
           steps:
             - none_language
         setup:
           runtime:
             type: image
             image:
               auto:
                 language: nodejs
                 versions:
                   - 8.16.0                      
         execution:
           onExecute:
             - echo TEST_FOR_SELECTED_VERSION
             - node -v
             
       - name: default_version
         type: bash
         requires:
           steps:
             - none_language
         setup:
           runtime:
             type: image
             image:
               auto:
                 language: nodejs                  
         execution:
           onExecute:
             - echo - echo TEST_FOR_DEFAULT_VERSION
             - node -v
