pipelines:
  - name: pipeline_S_PS_Language_0003
    steps:
      - name: S_PS_Language_0003
        type: PowerShell
        configuration:
          nodePool: win_2019
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - 11
        execution:
          onExecute:
#             - dotnet --version
#              - if($(dotnet --version) -ne "3.1.102"){
#                Write-Error "Stop" -ErrorAction Stop
#                }
            - java -version
            - if($(java -version) -ne ""openjdk 11.0.2 2019-01-15" "OpenJDK Runtime Environment 18.9 (build 11.0.2+9)" "OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)""){
              Write-Error "Stop" -ErrorAction Stop
              }
#             - if($(java -version) -Like "*openjdk version "11.0.2" 2019-01-15*"){ write-output "working" }
#               else { Write-Error "Stop" -ErrorAction Stop} 
#             - if($(java --version) -ne "*11.0.2*"){ write-output "working" } else {
#               Write-Error "Stop" -ErrorAction Stop
#               } 
#             - if($(java --version) -ne "openjdk 11.0.2 2019-01-15 ,
#               OpenJDK Runtime Environment 18.9 (build 11.0.2+9) ,
#               OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)"){
#               Write-Error "Stop" -ErrorAction Stop
#               }  
#             - source /root/.gvm/scripts/gvm
#             - gvm list
#             - gvm use 1.11
#             
#             - gcc --version
            - go version
            - if($(go version) -ne "go version go1.12.14 windows/amd64"){
              Write-Error "Stop" -ErrorAction Stop
              }
#             - java -version
#             - if($(clang --version) -ne "clang version 9.0.0 (tags/RELEASE_900/final) Target: x86_64-pc-windows-msvc Thread model: posix InstalledDir: C:\Program Files\LLVM\bin"){
#               Write-Error "Stop" -ErrorAction Stop
#               }
     
#             - |
#               [[ "$(node --version)" == *"10.18.0"* ]]
#             - gci env:*
#             - ls Env:
#             - get-childitem -path env:* | get-stepname
#             -  ("$java -version === $13.0.1")
#             - "java -version[]" == "13.0.1[]"
#             - get-childitem env
#             - Get-Variable | format-table
#             - java -version
#             - ant -version
#             - mvn -v
#             - gradle -v
#             - node -v
#             - npm --version
            
#             - |
#               [[ "$(java -version)" == *"13.0.1"* ]]



# resources:
#   - name: test1234
#     type: GitRepo
#     configuration:
#       gitProvider: github1
#       path: Ranjansingh41/test
      
# pipelines:
#   - name: pipelines
#     steps:
#       - name: S_Bash1
#         type: Bash
#         configuration:
#           inputResources:
#             - name: test1234
#         execution:
#           onExecute:
#             - echo "hi"
#       - name: S_Bash2
#         type: Bash
#         configuration:
#           inputSteps:
#             - name: S_Bash1
#         execution:
#           onExecute:
#             - echo "executing step..."
            
#       - name: S_Bash3
#         type: Bash
#         configuration:
#           inputResources:
#             - name: test1234
#         execution:
#           onExecute:
#             - echo "hi"
#       - name: S_Bash4
#         type: Bash
#         configuration:
#           inputSteps:
#             - name: S_Bash3
#         execution:
#           onExecute:
#             - echo "executing step..."
