resources:
  - name: npm_project
    type: GitRepo
    configuration:
      gitProvider: ranjan_github
      path: ranjansingh41/j-sample-node
#       sha: npmtest.yml
       
  - name: publish_info
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildNumber: 1
      buildName: npm-testing
      
  - name: npm_build_promote
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildNumber: 1
      buildName: npm-testing
  
  - name: my_releaseBundle 
    type: ReleaseBundle
    configuration:
      sourceDistribution: dist 
      name: test-npm-local
      version: 4.0.2
      isSigned: false
      
  - name: my_signed_releaseBundle
    type: ReleaseBundle
    configuration:
      sourceDistribution: dist 
      name: test-npm-local
      version: v1.0.0
#       isSigned: false  

  - name: distribution_rule_npm
    type: DistributionRule
    configuration:
      sourceDistribution: dist
      cityName: "*"
      serviceName: "*"
      siteName: "*"
      countryCodes:
        - IN  
      
pipelines:
  - name: test_pipeline_ranjan
    steps:
      - name: start_npm_build
        type: NpmBuild
        configuration:
          repositoryName: test-npm-local
#           nodepool: ubuntu16
          sourceLocation: .
          inputResources:
            - name: npm_project
          integrations:
            - name: varsha_artifactory
            
      - name: start_npm_pub_autopub_true
        type: NpmPublish
        configuration:
          repositoryName: test-npm-local
#           nodepool: ubuntu16
          autoPublishBuildInfo: true
          inputSteps:
            - name: start_npm_build
          integrations:
            - name: varsha_artifactory
          outputResources:
            - name: publish_info
            
      - name: promote
        type: PromoteBuild
        configuration:
          targetRepository: test-npm-local
#           nodepool: ubuntu16
          inputResources:
            - name: publish_info
#               trigger: false
          outputResources:
            - name: npm_build_promote 
            
      - name: bundle
        type: CreateReleaseBundle
        configuration:
          dryRun: false
          releaseBundleName: bundle_relese
          releaseBundleVersion: 4.0.2
#           nodepool: ubuntu16
          releaseNotes:         
            content: bundle_test 
            syntax:  plain_text 
          inputResources:
            - name: npm_build_promote 
#             - name: my_aql  # one Aql 
          outputResources:
            - name: my_releaseBundle
            
      - name: Sign_Release_Bundle
        type: SignReleaseBundle
        configuration: 
#           nodepool: ubuntu16
          inputResources:
            - name: my_releaseBundle  # one ReleaseBundle is mandatory
              #trigger: false    # default true
          outputResources:
            - name: my_signed_releaseBundle    # ReleaseBundle resource
            
      - name: distribute_signed_release_bundleo
        type: DistributeReleaseBundle
        configuration:
          dryRun: false
          inputResources:
            - name: my_signed_releaseBundle
            - name: distribution_rule_npm
          integrations: 
            - name: dist
