resources:
  - name: test10
    type: gitRepo
    repoPath: ranjansingh41/test
    configuration:
      integrationName: ranajn_github
#       files:
#         only: README|install.sh|node
      branches:
        only: master
#       tags:
#         only: tagv*
#       buildOn:
#         commit: false
#       shallowDepth: 2
    initialVersion:
      sha: master
      
# resources:
#   - name: fileIntegrationResource
#     type: file
#     fileLocation: <string>
#     fileName: <string>  # optional
#     configuration:      
#       integrationName: fileIntegration
#     initialVersion:
#       fileDtTm: <string>  # optional

pipelines:
  - name: pipeline10
    setup:
      environmentVariables:
        readOnly:
          ENV1: value1
          ENV2: value2 
    steps:
       - name: none_language
         type: bash
         setup:
          environmentVariables:
            normal:
              ENV1: value1
              ENV2: value2          
           runtime:
             type: image
            # image:
               #auto:
#                  language: none            
         execution:
           onExecute:
             - echo TEST_FOR_NONE
#              - node -v

       - name: selected_version
         type: bash
#          setup:
#            environmentVariables:
#              readOnly:
#                ENV1: value1
#                ENV2: value2 
         triggeredBy:
#          requires:
           steps:
             - none_language
         setup:
           runtime:
             type: image
             image:
               auto:
                 language: nodejs
                 versions:
                   - 8.16.0                      
         execution:
           onExecute:
             - echo TEST_FOR_SELECTED_VERSION
             - node -v
             
       - name: default_version
         type: bash
         triggeredBy:
#          requires:
           steps:
             - none_language
         setup:
           runtime:
             type: image
             image:
               auto:
                 language: nodejs                  
         execution:
           onExecute:
             - echo - echo TEST_FOR_DEFAULT_VERSION
             - node -v
