resources:
  - name: mvnBuild_info
    type: BuildInfo
    configuration:
      sourceArtifactory: varsha_artifactory
      buildName: mvn_sample_build
      buildNumber: 1
      
pipelines:
  - name: ranjanmvn
    steps:
      - name: mvnBuild_sample
        type: MvnBuild
        configuration:
          affinityGroup: mvnbuild
#           nodePool: ubuntu16
          sourceLocation: ./artifactory-maven-plugin-example
          mvnCommand: clean install -f ./pom.xml
          configFileLocation: .
          configFileName: mvn-art-config
          inputResources:
            - name: mvn_repo
          inputSteps:
            - name: mvnBuild_info1
          integrations:
            - name: varsha_artifactory
            - name: varsha_slack
          runtime:            
            type: image
            image:
              custom:
                name: drydock/u16java
                tag: master
        execution:
          onStart:
            - javac -version
            - mvn --version
          onSuccess:
            - send_notification varsha_slack      
