resources:
  - name: app1
    type: gitRepo
    repoPath: ranjansingh41/test
    configuration:
      integrationName: github
      branches:
        only: master
    initialVersion:
      sha: master

pipelines1:
  - name: pipeline
    steps:
       - name: none_language
         type: bash
         setup:
           runtime:
             type: image
            # image:
               #auto:
#                  language: none            
         execution:
           onExecute:
             - echo TEST_FOR_NONE
#              - node -v

       - name: selected_version
         type: bash
         requires:
           steps:
             - none_language
         setup:
           runtime:
             type: image
             image:
               auto:
                 language: nodejs
                 versions:
                   - 8.16.0                      
         execution:
           onExecute:
             - echo TEST_FOR_SELECTED_VERSION
             - node -v
             
       - name: default_version
         type: bash
         requires:
           steps:
             - none_language
         setup:
           runtime:
             type: image
             image:
               auto:
                 language: nodejs   
         triggeredBy:
          resources:
            - app1
         execution:
           onExecute:
             - echo - echo TEST_FOR_DEFAULT_VERSION
             - node -v
             
       - name: utility_step
         type: bash
         triggeredBy:
           resources:
             - app1
         requires:
           integrations:
             - slackNotify
         execution:
           onExecute:
             - update_commit_status app1 --status processing --message "updated in utility step" --context $STEP_NAME
             - send_notification slackNotify

             pipelines:
               - name: pipeline
                 steps:
                    - name: none_language
                      type: bash
                      setup:
                        runtime:
                          type: image
                         # image:
                            #auto:
             #                  language: none            
                      execution:
                        onExecute:
                          - echo TEST_FOR_NONE
             #              - node -v

                    - name: selected_version
                      type: bash
                      requires:
                        steps:
                          - none_language
                      setup:
                        runtime:
                          type: image
                          image:
                            auto:
                              language: nodejs
                              versions:
                                - 8.16.0                      
                      execution:
                        onExecute:
                          - echo TEST_FOR_SELECTED_VERSION
                          - node -v
                          
                    - name: default_version
                      type: bash
                      requires:
                        steps:
                          - none_language
                      setup:
                        runtime:
                          type: image
                          image:
                            auto:
                              language: nodejs   
                      triggeredBy:
                       resources:
                         - app1
                      execution:
                        onExecute:
                          - echo - echo TEST_FOR_DEFAULT_VERSION
                          - node -v
                          
                    - name: utility_step
                      type: bash
                      triggeredBy:
                        resources:
                          - app1
                      requires:
                        integrations:
                          - slackNotify
                      execution:
                        onExecute:
                          - update_commit_status app1 --status processing --message "updated in utility step" --context $STEP_NAME
                          - send_notification slackNotify
pipelines:
  - name: pipeline
    steps:
       - name: none_language
         type: bash
         setup:
           runtime:
             type: image
            # image:
               #auto:
#                  language: none            
         execution:
           onExecute:
             - echo TEST_FOR_NONE
#              - node -v

       - name: selected_version
         type: bash
         requires:
           steps:
             - none_language
         setup:
           runtime:
             type: image
             image:
               auto:
                 language: nodejs
                 versions:
                   - 8.16.0                      
         execution:
           onExecute:
             - echo TEST_FOR_SELECTED_VERSION
             - node -v
             
       - name: default_version
         type: bash
         requires:
           steps:
             - none_language
         setup:
           runtime:
             type: image
             image:
               auto:
                 language: nodejs   
         triggeredBy:
          resources:
            - app1
         execution:
           onExecute:
             - echo - echo TEST_FOR_DEFAULT_VERSION
             - node -v
             
       - name: utility_step
         type: bash
         triggeredBy:
           resources:
             - app1
         requires:
           integrations:
             - slackNotify
         execution:
           onExecute:
             - update_commit_status app1 --status processing --message "updated in utility step" --context $STEP_NAME
             - send_notification slackNotify

pipelines2:
  - name: pipeline
    steps:
       - name: none_language
         type: bash
         setup:
           runtime:
             type: image
            # image:
               #auto:
#                   language: none            
         execution:
           onExecute:
             - echo TEST_FOR_NONE
#               - node -v

       - name: selected_version
         type: bash
         requires:
           steps:
             - none_language
         setup:
           runtime:
             type: image
             image:
               auto:
                 language: nodejs
                 versions:
                   - 8.16.0                      
         execution:
           onExecute:
             - echo TEST_FOR_SELECTED_VERSION
             - node -v

       - name: default_version
         type: bash
         requires:
           steps:
             - none_language
         setup:
           runtime:
             type: image
             image:
               auto:
                 language: nodejs   
         triggeredBy:
          resources:
            - app1
         execution:
           onExecute:
             - echo - echo TEST_FOR_DEFAULT_VERSION
             - node -v

       - name: utility_step
         type: bash
         triggeredBy:
           resources:
             - app1
         requires:
           integrations:
             - slackNotify
         execution:
           onExecute:
             - update_commit_status app1 --status processing --message "updated in utility step" --context $STEP_NAME
             - send_notification slackNotify 

             
             
             
             
             
