resources:
  - name: test10
    type: gitRepo
    repoPath: ranjansingh41/test
    configuration:
      integrationName: ranjan_github
#       files:
#         only: README|install.sh|node
      branches:
        only: master
#       tags:
#         only: tagv*
#       buildOn:
#         commit: false
#       shallowDepth: 2
    version:
      sha: master
      
# resources:
#   - name: test5
#     type: file
#     configuration:      
#       integrationName: ranjan_file
#     version:
#       fileLocation: <string> # optional
#       fileName: <string> # optional
#       fileDtTm: <string>  # optional
#       ### JFrog artifactory specific specs ###
#       pattern: <string> # optional
#       aql: <string> # optional
#       target: <string> # optional
#       props: <string> # optional
#       recursive: <boolean> # optional
#       flat: <boolean> # optional
#       excludePatterns: <string> # optional
#       archiveEntries: <string> # optional
#       build: <string> # optional
#       sortBy: <string> # optional
#       sortOrder: <string> # optional
#       limit: <integer> # optional
#       offset: <integer> # optional
      
pipelines:
  - name: pipeline12
#     setup:
#       environmentVariables:
#         readOnly:
#           NameF: ranjan
#           NameL: kumar
    steps:    
      - name: test1
        type: bash
        configuration:
          affinityGroup: sita
#           priority: <[0-10000]>
#            timeoutSeconds: 1/2 
          nodePool: ankul_nodes
#           environmentVariables:
#             normal:
#               NameF: singh
#               NameL: umar  
        setup:
          runtime:
            type: image
 #             type: host
            image:
 #                 auto:
 #                   language: nodejs
 #                   versions: 10.15.3
             custom:
               name: drydock/u16node
               tag: master
        triggeredBy:
          resources:
            - test10
        execution:
          onExecute:
            - echo $?
            - echo "test1"
            - echo "NameL=$NameL"
            - echo "NameF=$NameF"
            - nvm list
            - node --version
            
      - name: default_version
        type: bash
        configuration:
            affinityGroup: ram
            nodePool: ankul_nodesew
        triggeredBy:
         resources:
           - test10
        setup:
         runtime:
           type: image
           image:
             auto:
               language: nodejs                  
        execution:
           onExecute:
             - echo - echo TEST_FOR_DEFAULT_VERSION
             - node -v
