resources:
  - name: simple_test
    type: GitRepo
    configuration:
      gitProvider: ranjan_github
      path: Ranjansingh41/test 
      
pipelines:
  - name: pipeline_ranjan
    steps:
      - name: node
        type: Bash
        configuration:
#           nodePool: node-RHEL-8 
#           inputResources:
#             - name: simple_test
#           outputResources:
#             - name: simple_test1
          runtime:
            type: image
            image:
#               auto:
#                 language: go
#                 Versions: 
#                  - 1.12.6
              custom:
                name: ankul/u16
                tag: master
        execution:
#           onStart:
#             - printen
          onExecute:
            - printenv
#           onFailure:
#             - echo "test fail"
#           onComplete: #always
#             - echo "Cleaning up some stuff"


#       - name: go
#         type: Bash
#         configuration:
#           inputSteps:
#             - name: nodes
#           runtime:
#             type: image
#             image:
#               auto:
#                 language: go
#                 versions:
#                   - 1.12.6
# #               custom:
# #                 name: dryd/u18go
# #                 tag: master
# #                 autoPull: false
#         execution:
#           onExecute:
#             - source /root/.gvm/scripts/gvm
#             - gvm list
#             - go version
#             - gvm use 1.11.11 
#             - go version
#             - gvm use 1.12.6
#             - go version                
#       - name: cpp
#         type: Bash
#         configuration:
# #           nodePool: vijay_node           
#           inputSteps:
#             - name: go      
#           runtime:
#             type: image
#             image:
#               auto:
#                 language: c
#                 versions:
#                   - 8.0.0
# #               custom:
# #                 name: drydock/u18cpp
# #                 tag: master
# #                 autoPull: true
#         execution:
#           onExecute:
#             - gcc --version
#             - clang --version
