resources:
  - name: test10
    type: gitRepo
    repoPath: ranjansingh41/test
    configuration:
      integrationName: ranjan_github
#       files:
#         only: README|install.sh|node
      branches:
        only: master
#       tags:
#         only: tagv*
#       buildOn:
#         commit: false
#       shallowDepth: 2
    version:
      sha: master
      
pipelines:
  - name: pipeline12
    steps:    
      - name: test1
        type: bash
        setup:
          environmentVariables:
            readOnly:
              ENV1: ranjan
              ENV2: kumar
        triggeredBy:
          resources:
            - test10    
          runtime:
            type: image
            image:
#               auto:
#                 language: nodejs
#                 versions:
#                   - 10.15.3
              custom:
                name: drydock/u16node
                tag: master
        execution:
          onExecute:
            - write_output test10 key56445004=value1236600
#         outputResources:
#           - test10
  
            
      - name: default_version
        type: bash
#         configuration:
#             affinityGroup: sita 
#             nodePool: kermit_ubuntu_pool
        triggeredBy:
         steps:
           - test1
        setup:
         runtime:
           type: image
           image:
             auto:
               language: nodejs                  
        execution:
           onExecute:
             - echo - echo TEST_FOR_DEFAULT_VERSION
             - node -v
