resources:
  - name: npm_project
    type: GitRepo
    configuration:
      gitProvider: ranjan_github
      path: ranjansingh41/j-sample-node
       
  - name: publish_info
    type: BuildInfo
    configuration:
      sourceArtifactory: art_aws_demo_2
      buildNumber: 1
      buildName: npm-testing
      
  - name: npm_build_promote
    type: BuildInfo
    configuration:
      sourceArtifactory: art_aws_demo_2
      buildNumber: 1
      buildName: npm-testing
      
pipelines:
  - name: test_pipeline_ranjan
    steps:
      - name: start_npm_build
        type: NpmBuild
        configuration:
          repositoryName: npm-remote-cache
#           nodepool: ubuntu16
          sourceLocation: .
          inputResources:
            - name: npm_project
          integrations:
            - name: art_aws_demo_2
        execution:        
          onSuccess:
            - send_notification Demo_slack
          onFailure:
            - send_notification Demo_slack
          onComplete:
            - send_notification Demo_slack
    
      - name: start_npm_pub_autopub_true
        type: NpmPublish
        configuration:
          repositoryName: npm-remote-cache
#           nodepool: ubuntu16
          autoPublishBuildInfo: true
          inputSteps:
            - name: start_npm_build
          integrations:
            - name: art_aws_demo_2
          outputResources:
            - name: publish_info
        execution:        
          onSuccess:
            - send_notification Demo_slack
          onFailure:
            - send_notification Demo_slack
          onComplete:
            - send_notification Demo_slack
             
      - name: promote
        type: PromoteBuild
        configuration:
          targetRepository: promote-test
#           nodepool: ubuntu16
          inputResources:
            - name: publish_info
#               trigger: false
          outputResources:
            - name: npm-demo 
        execution:        
          onSuccess:
            - send_notification Demo_slack
          onFailure:
            - send_notification Demo_slack
          onComplete:
            - send_notification Demo_slack    
     
          
