resources:
  - name: test10
    type: gitRepo
    repoPath: ranjansingh41/test
    configuration:
      integrationName: ranajn_github
#       files:
#         only: README|install.sh|node
      branches:
        only: master
#       tags:
#         only: tagv*
#       buildOn:
#         commit: false
#       shallowDepth: 2
    initialVersion:
      sha: master
      
# resources:
#   - name: fileIntegrationResource
#     type: file
#     fileLocation: <string>
#     fileName: <string>  # optional
#     configuration:      
#       integrationName: fileIntegration
#     initialVersion:
#       fileDtTm: <string>  # optional

pipelines:
  - name: pipeline49
    setup:
      environmentVariables:
        readOnly:
          ENV1: value1
          ENV2: value2 
       - name: none_language
         type: bash
         setup:
           runtime:
             type: image
            # image:
               #auto:
#                  language: none            
         execution:
           onExecute:
#              - save_run_state pipelines.yml my_file
             - echo ranjan
#              - node -v

       - name: selected_version
         type: bash
         triggeredBy:
#          requires:
           steps:
             - none_language
          setup:
            environmentVariables:
              readOnly:
                ENV1: value3
                ENV2: value4    
           runtime:
             type: image
             image:
               auto:
                 language: nodejs
                 versions:
                   - 8.16.0                      
         execution:
           onExecute:
#              - restore_run_state  my_file pipelines.yml
             - node -v
             
       - name: default_version
         type: bash
         triggeredBy:
#          requires:
           steps:
             - selected_version
         setup:
           runtime:
             type: image
             image:
               auto:
                 language: nodejs                  
         execution:
           onExecute:
             - echo - echo TEST_FOR_DEFAULT_VERSION
             - node -v
  
