pipelines:
    steps:
      - name: ag_step_1
        type: Bash
        configuration:
          affinityGroup: together
        execution:
          onExecute:
            - echo $"hi"
      - name: ag_step_2
        type: Bash
        configuration:
          affinityGroup: together
          inputSteps:
             - name: ag_step_1
        execution:
          onExecute:
            - echo $"hello"
