# pipelines:
#   - name: pipelines_S_Bash
#     steps:
#       - name: S_Bash5
#         type: PowerShell
#         configuration:
#           nodePool: ranjan_window
# #            inputSteps:
# #             - name: S_Bash4
#         execution:
#           onExecute:
#             - write-output "executing step..."
# #       - name: S_Bash6
#         type: PowerShell
#         configuration:
#           nodePool: ranjan_window
# #           inputSteps:
# #             - name: S_Bash5
#         execution:
#           onExecute:
#             - write-output "executing step..."
#       - name: S_Bash7
#         type: PowerShell
#         configuration:
#           nodePool: ranjan_window
# #           inputSteps:
# #             - name: S_Bash6
#         execution:
#           onExecute:
#             - write-output "executing step..."

  
resources:  
#   - name: image
#     type: Image
#     configuration:
#        registry: gcp
#        imageName: gcr.io/ship-rc/ubuntu
#        imageTag: latest
#        autoPull: true  


  - name: git2
    type: GitRepo
    configuration:
      path: Ranjansingh41/test
      gitProvider: github

#   - name: S_Bash_0007_propertyBag
#     type: PropertyBag
#     configuration:
#       property1: "test"

pipelines:
  - name: pipelines_S_Bash
    steps:
      - name: test_aws
        type: Bash
        configuration:
          nodePool: u18-eu-west
          inputResources:
            - name: git2
        execution:
          onExecute:
            - echo "executing step..."
            
      - name: S_Bash5
        type: Bash
        configuration:
          nodePool: ranjan_azure
          inputSteps:
            - name: test_aws
#           inputResources:
#             - name: git2
        execution:
          onExecute:
            - echo "executing step..."




