resources:
  - name: real_npm_project
    type: GitRepo
    configuration:
      gitProvider: ranjan_github
      path: ranjansingh41/j-sample-node
      sha: npmtest.yml
      
      
  - name: npm_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: varsha_artifactory
      buildNumber: 1
      buildName: npm-testing
      
  - name: npm_build_promote
    type: Bundle
    configuration:
      sourceArtifactory: varsha_artifactory
      buildNumber: 1
      buildName: npm-testing
  
  - name: npm_bundle
    type: BuildInfo
    configuration:
      sourceArtifactory: varsha_artifactory
      buildNumber: 1
      buildName: npm-testing  

pipelines:
  - name: test_pipeline_ranjan
    steps:
      - name: start_npm_build
        type: NpmBuild
        configuration:
          repositoryName: ranjan_npmtest
          sourceLocation: .
          inputResources:
            - name: real_npm_project
          integrations:
            - name: varsha_artifactory
            
      - name: start_npm_pub_autopub_true
        type: NpmPublish
        configuration:
          repositoryName: ranjan_npmlocal
          autoPublishBuildInfo: true
          inputSteps:
            - name: start_npm_build
          integrations:
            - name: varsha_artifactory
          outputResources:
            - name: npm_build_info
            
      - name: promote
        type: PromoteBuild
        configuration:
          targetRepository: ranjan_npmlocal
          inputResources:
            - name: npm_build_info
          outputResources:
            - name: npm_build_promote 
            
      - name: bundle
        type: CreateReleaseBundle
        configuration:
          releaseBundleName: bundle_relese
          releaseBundleVersion: 1.0.0
          releaseNotes:         
            content: bundle_test 
            syntax:  plain_text 
          inputResources:
            - name: npm_build_promote 
#             - name: my_aql  # one Aql 
          outputResources:
            - name: npm_bundle



     
