resources:
  - name: test18
    type: gitRepo
    repoPath: ranjansingh41/test
    configuration:
      integrationName: ranjan_github
#       files:
#         only: README|install.sh|node
      branches:
        only: enc.yml
#       tags:
#         only: tagv*
#       buildOn:
#         commit: false
#       shallowDepth: 2
    version:
      sha: master
      
  - name: pvtrepo
    type: gitRepo
    repoPath: Ranjansingh41/pvtRepo
    configuration:
      integrationName: ranjan_github
#       files:
#         only: README|install.sh|node
      branches:
        only: master
#       tags:
#         only: tagv*
#       buildOn:
#         commit: false
#       shallowDepth: 2
    version:
      sha: master
  
            
      
      
      
pipelines:
  - name: pipeline19
    steps:    
      - name: test14
        type: bash
#         configuration:
#           affinityGroup: sita
# #           priority: <[0-10000]>
# #            timeoutSeconds: 1/2 
#           nodePool: kermit_ubuntu_pool
# #           environmentVariables:
#             normal:
#               NameF: singh
#               NameL: umar  
        setup:
          environmentVariables:
            readOnly:
              ENV1: ranjan
              ENV2: kumar
          runtime:
            type: image
            image:
#               auto:
#                 language: nodejs
#                 versions:
#                   - 10.15.3
              custom:
                name: drydock/u16node
                tag: master
#         requires:
#           resources:
#            - test10
        requires:
          integrations:
            - ranjan_slack
        triggeredBy:
          resources:
            - test18
            - pvtrepo
        execution:
          onExecute:
            - pwd
            - pushd $res_pvtrepo_resourcePath
            - echo $res_pvtrepo_resourcePath
            - openssl genrsa -out key.pem 1024 
            - openssl rsa -in key.pem -text -noout
            - openssl rsa -in key.pem -pubout -out pub.pem 
            - openssl rsa -in pub.pem -pubin -text -noout
            - encrypt_file enc.txt --key pub.pem
            - cat encrypted
            - decrypt_file encrypted --key key.pem
            - popd
            - pushd $res_test18_resourcePath
            - read_json secret.json "TOP_SECRET_CONFIDENTIAL_FORMULA"
            - popd
            - pushd $res_test18_resourcePath
            - cache_files README.md my_file
            - restore_cache my_file README.md
            - add_run_variable ranjan=kumar
            - send_notification ranjan_slack
            
#             - write_output test10 key564454=value123
#             - bump_semver v1.0 major
#             - compare_git --resource test10 --commit-range HEAD~2..HEAD
#             - node --version
#             - printenv
#             - retry_command nod --version
#             - update_commit_status test10 --status success --message "updated u16node" --context $STEP_NAME
#             - compare_git --commit-range da42305b1d5205faad8a8d06ee8e342c00ee51f1..master --path $STEP_DEPENDENCY_STATE_DIR/resources/test10
#         outputResources:
#           - test10
  
            
      - name: default_version
        type: bash
#         configuration:
#             affinityGroup: sita 
#             nodePool: kermit_ubuntu_pool
        triggeredBy:
         steps:
           - test14
        setup:
         runtime:
           type: image
           image:
             auto:
               language: nodejs                  
        execution:
           onExecute:
             - echo - echo TEST_FOR_DEFAULT_VERSION
             - node --version
             - echo $ranjan



             
             
