resources:
  - name: test5
    type: gitRepo
    repoPath: Ranjansingh41/test
    configuration:
      integrationName: ranajn_github
      branches:
        only: master
    initialVersion:
      sha: master
  
pipelines:
  - name: runtime1
    type: bash
    configuration:
          nodePool: kermit_centos_pool 
    setup: 
      environmentVariables:
        readOnly:
          Number: 27   
      runtime:       
        type: image
        image:
          auto:
            language: none
#             versions:
#               - 10.15.3
#           custom:
#             name: "drydock/u16node"
#             tag: "master"
#             options: "--name ranjan"
    steps:    
      - name: test1
        type: bash
        setup: 
          environmentVariables:
            normal:
              d: 27 
#         setup:
#           runtime:
#             type: image
#             image:
#              custom:
#                name: drydock/u16node
#                tag: master
        triggeredBy:
          resources:
            - test5
        execution:
          onExecute:
            - echo "hi"
            - docker pull drydock/u16node:master
            - nvm list
            - node --version
