resources:
  - name: git_vijay
    type: GitRepo
    configuration:
      gitProvider: ranjan_github
      path: Ranjansingh41/test
   
  - name: helm_repo
    type: HelmChart
    configuration: 
      sourceArtifactory: varsha_art
      repository: helm-local
      chart: test
      version: 1.0.0

pipelines:
  - name: test_helm_native

    steps:
      - name: helm_publish_stepss
        type: HelmPublish
        configuration:
          chartPath: stable/tomcat
 
          inputResources:
            - name: ranjan_github                   
          outputResources:
            - name: helm_repo                  # required
 
        execution:
          onStart:
            - echo "Preparing for work..."
            - printenv
          onSuccess:
            - echo "Job well done!"
            - printenv
          onFailure:
            - echo "uh oh, something went wrong"
            - printenv
          onComplete: #always
            - echo "Cleaning up some stuff"
            - printenv
