pipelines:
  - name: pipelinesag
    steps:
      - name: agstep1
        type: Bash
        configuration:
          affinityGroup: together
        execution:
          onExecute:
            - echo $"hi"
      - name: agstep2
        type: Bash
        configuration:
          affinityGroup: together
          inputSteps:
             - name: agstep1
        execution:
          onExecute:
            - echo $"hello"
      - name: agstep3
        type: Bash
        configuration:
          affinityGroup: together
          inputSteps:
             - name: agstep2
        execution:
          onExecute:
            - echo $"hello"      
