resources:
  - name: mvnBuild_inf
    type: BuildInfo
    configuration:
      sourceArtifactory: varsha_artifactory
      buildName: mvn_sample_build
      buildNumber: 1
      
  - name: mvnBuild_info09
    type: BuildInfo
    configuration:
      sourceArtifactory: varsha_artifactory
      buildName: mvn_scan
      buildNumber: 2
      
#   - name: mvn_build_promote
#     type: BuildInfo
#     configuration:
#       sourceArtifactory: varsha_artifactory
#       buildNumber: 3
  
#   - name: my_releaseBundle 
#     type: ReleaseBundle
#     configuration:
#       sourceArtifactory: varsha_artifactory
#       name: ranjan
#       version: v1.0.0
#       isSigned: false    
      
pipelines:
  - name: mvntest_ranjan
    steps:
      - name: mvnBuild_sample
        type: MvnBuild
        configuration:
          affinityGroup: mvnbuild
#           nodePool: ubuntu16
          sourceLocation: ./artifactory-maven-plugin-example
          mvnCommand: clean install -f ./pom.xml
          configFileLocation: .
          configFileName: mvn-art-config
          nodePool: ubuntu16
          inputResources:
            - name: mvn_repo
#           inputSteps:
#             - name: mvnBuild_info1
          integrations:
            - name: varsha_artifactory
            - name: varsha_slack
          runtime:            
            type: image
            image:
              custom:
                name: pipelines-docker.jfrog.io/jfrog/pipelines-u16java
                tag: 0.9.0
        execution:
          onStart:
            - javac -version
            - mvn --version
          onSuccess:
            - send_notification varsha_slack
            
      - name: mvnBuild_publish
        type: PublishBuildInfo
        configuration:
          affinityGroup: mvnbuild
#           nodePool: ubuntu16
          integrations:
            - name: varsha_slack
          inputSteps:
            - name: mvnBuild_sample
          outputResources:
            - name: mvnBuild_info09
        execution:
          onSuccess:
            - send_notification varsha_slack          
            
#       - name: mvnPromote
#         type: PromoteBuild
#         configuration:
#           targetRepository: bindu_mvn_local
#           inputResources:
#             - name: mvn_build_promote
#           outputResources:
#             - name: mvn_build_promote
#       - name: mvnCreatebundle
#         type: CreateReleaseBundle
#         configuration:
#           releaseBundleName: mvnbundle
#           releaseBundleVersion: v1.1.1
#           dryRun: false
#           sign: false
#           description: test mvn description
#           inputResources:
#             - name: mvn_build_promote
#           outputResources:
#             - name: my_releaseBundle
