pipelines:
  - name: RanjanBash
    steps:
      - name: Ranjan
        type: Bash
        configuration:   
          runtime:       
            type: image
            image:
              custom:
                name: vijaydocker1991/u18node
                tag: gotesting
                options: " "          
        execution:
          onExecute:
            - printenv
