resources:
  - name: simple_test
    type: GitRepo
    configuration:
      gitProvider: ranjan_github
      path: Ranjansingh41/test 
      
pipelines:
  - name: pipeline_ranjan1
    steps:
      - name: node
        type: Bash
        configuration:
          inputResources:
            - name: simple_test
          runtime:
            type: image
            image:
#               auto:
#                 language: nodejs
#                 versions:
#                   - 10.15.3
              custom:
                name:  pipelines-docker.jfrog.io/jfrog/pipelines-c7go
                tag: 0.9.1
                autoPull: false
        execution:
          onExecute:
#             - go version
            - jfrog --version
            - kubectl version --client
