resources:
  - name: simple_test
    type: GitRepo
    configuration:
      gitProvider: git58
      path: Ranjansingh41/test 
      
pipelines:
  - name: pipeline_ranjan1
    steps:
      - name: node
        type: Bash
        configuration:
          inputResources:
            - name: simple_test
          runtime:
            type: image
            image:
#               auto:
#                 language: nodejs
#                 versions:
#                   - 10.15.3
              custom:
                name:  pipelines-u16node
                tag: 0.9.1
                autoPull: true
        execution:
          onExecute:
            - nvm list
            - node --version
            - kubctl --version
