resources:
  - name: image_test
    type: Image
    configuration:
       registry: docker
       sourceRepository: docker-local-test  # required if Docker registry is Artifactory
#        region: <string> # required if registry is AWS
       imageName: ranjansingh/python
       imageTag: latest 
#        autoPull: <boolean> (default false)

      
pipelines:
  - name: pipeline_ranjan1
    steps:
      - name: node
        type: Bash
        configuration:
          inputResources:
            - name: image_test
#           runtime:
#             type: image
#             image:
# #               auto:
# #                 language: nodejs
# #                 versions:
# #                   - 10.15.3
#               custom:
#                 name:  ankul/u16
#                 tag: master
# #                 autoPull: false
        execution:
          onExecute:
            - printenv
#             - nvm list
#             - jfrog --version
#             - kubectl version --client
