pipelines:
  - name: pipelinestest
#     configuration:
#       runtime:       
#         type: image
    steps:
      - name: test
        type: Bash
        configuration:
          nodePool: u18-us-west-2-dynamic
          runtime:
            type: image
            image:
#               auto:
#                 language: node
#                 versions:
#                   - 10.18.0
              custom:
                name: ubuntu      #gcr.io/ship-rc/ubuntu
                tag: latest
#                 sourceRepository: docker-local
                registry : aws
#                 region: us-east-1
                autoPull: true
        execution:
          onExecute:
            - echo "Hi"
