resources:
  - name: simple_test
    type: GitRepo
    configuration:
      gitProvider: ranjan_github
      path: Ranjansingh41/test 
      
pipelines:
  - name: pipeline_ranjan1
    steps:
      - name: node
        type: Bash
        configuration:
          inputResources:
            - name: simple_test
          runtime:
            type: image
            image:
              auto:
                language: nodejs
                versions:
                  - 10.15.3
#               custom:
#                 name: drydock/u16node
#                 tag: master
#                 autoPull: false
        execution:
          onExecute:
            - nvm list
            - node --version 
            - add_run_variables imageTag="master"
